<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Extensions.OpenAI" Version="[3.0.0-beta.1]" />
    <PackageReference Include="Azure.AI.Projects" Version="[3.0.0-beta.3]" />
    <PackageReference Include="Azure.AI.Projects.Agents" Version="[3.0.0-beta.3]" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
  </ItemGroup>

</Project>
