/*
 * Speech Services API v3.0-beta1
 * Speech Services API v3.0-beta1.
 *
 * OpenAPI spec version: v3.0-beta1
 * Contact: crservice@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IFailedDownloadItem;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DownloadTasksResponseV3
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-02T13:09:27.002+08:00")
public class DownloadTasksResponseV3 {
  @SerializedName("zipFileByteArray")
  private byte[] zipFileByteArray = null;

  @SerializedName("successfulFileCount")
  private Integer successfulFileCount = null;

  @SerializedName("failedDownloadList")
  private List<IFailedDownloadItem> failedDownloadList = null;

  public DownloadTasksResponseV3 zipFileByteArray(byte[] zipFileByteArray) {
    this.zipFileByteArray = zipFileByteArray;
    return this;
  }

   /**
   * The Zip file containing all you want. The caller need to convert this to ZipFile themselves
   * @return zipFileByteArray
  **/
  @ApiModelProperty(value = "The Zip file containing all you want. The caller need to convert this to ZipFile themselves")
  public byte[] getZipFileByteArray() {
    return zipFileByteArray;
  }

  public void setZipFileByteArray(byte[] zipFileByteArray) {
    this.zipFileByteArray = zipFileByteArray;
  }

  public DownloadTasksResponseV3 successfulFileCount(Integer successfulFileCount) {
    this.successfulFileCount = successfulFileCount;
    return this;
  }

   /**
   * The successfully downloaded file count
   * @return successfulFileCount
  **/
  @ApiModelProperty(required = true, value = "The successfully downloaded file count")
  public Integer getSuccessfulFileCount() {
    return successfulFileCount;
  }

  public void setSuccessfulFileCount(Integer successfulFileCount) {
    this.successfulFileCount = successfulFileCount;
  }

  public DownloadTasksResponseV3 failedDownloadList(List<IFailedDownloadItem> failedDownloadList) {
    this.failedDownloadList = failedDownloadList;
    return this;
  }

  public DownloadTasksResponseV3 addFailedDownloadListItem(IFailedDownloadItem failedDownloadListItem) {
    if (this.failedDownloadList == null) {
      this.failedDownloadList = new ArrayList<IFailedDownloadItem>();
    }
    this.failedDownloadList.add(failedDownloadListItem);
    return this;
  }

   /**
   * The failed download list
   * @return failedDownloadList
  **/
  @ApiModelProperty(value = "The failed download list")
  public List<IFailedDownloadItem> getFailedDownloadList() {
    return failedDownloadList;
  }

  public void setFailedDownloadList(List<IFailedDownloadItem> failedDownloadList) {
    this.failedDownloadList = failedDownloadList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DownloadTasksResponseV3 downloadTasksResponseV3 = (DownloadTasksResponseV3) o;
    return Arrays.equals(this.zipFileByteArray, downloadTasksResponseV3.zipFileByteArray) &&
        Objects.equals(this.successfulFileCount, downloadTasksResponseV3.successfulFileCount) &&
        Objects.equals(this.failedDownloadList, downloadTasksResponseV3.failedDownloadList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(zipFileByteArray), successfulFileCount, failedDownloadList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DownloadTasksResponseV3 {\n");
    
    sb.append("    zipFileByteArray: ").append(toIndentedString(zipFileByteArray)).append("\n");
    sb.append("    successfulFileCount: ").append(toIndentedString(successfulFileCount)).append("\n");
    sb.append("    failedDownloadList: ").append(toIndentedString(failedDownloadList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

