/*
 * Speech Services API v3.0-beta1
 * Speech Services API v3.0-beta1.
 *
 * OpenAPI spec version: v3.0-beta1
 * Contact: crservice@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * ICreateFolderDefinitionV3
 */
public class ICreateFolderDefinitionV3 {
  @SerializedName("parentId")
  private UUID parentId = null;

  @SerializedName("name")
  private String name = null;

  public ICreateFolderDefinitionV3 parentId(UUID parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * The parent folder id where you want to put your new folder under. Null means root path
   * @return parentId
  **/
  @ApiModelProperty(example = "00000000-0000-0000-0000-000000000000", value = "The parent folder id where you want to put your new folder under. Null means root path")
  public UUID getParentId() {
    return parentId;
  }

  public void setParentId(UUID parentId) {
    this.parentId = parentId;
  }

  public ICreateFolderDefinitionV3 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The created folder&#39;s name
   * @return name
  **/
  @ApiModelProperty(value = "The created folder's name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ICreateFolderDefinitionV3 icreateFolderDefinitionV3 = (ICreateFolderDefinitionV3) o;
    return Objects.equals(this.parentId, icreateFolderDefinitionV3.parentId) &&
        Objects.equals(this.name, icreateFolderDefinitionV3.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parentId, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ICreateFolderDefinitionV3 {\n");
    
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

