/*
 * Speech Services API v3.0-beta1
 * Speech Services API v3.0-beta1.
 *
 * OpenAPI spec version: v3.0-beta1
 * Contact: crservice@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * IFailedDownloadItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-02T13:09:27.002+08:00")
public class IFailedDownloadItem {
  @SerializedName("fileName")
  private String fileName = null;

  /**
   * The failed type
   */
  @JsonAdapter(FailedTypeEnum.Adapter.class)
  public enum FailedTypeEnum {
    NONE("None"),
    
    PLAINTEXT("PlainText"),
    
    SSML("SSML"),
    
    AUDIO("Audio");

    private String value;

    FailedTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FailedTypeEnum fromValue(String text) {
      for (FailedTypeEnum b : FailedTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<FailedTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FailedTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FailedTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return FailedTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("failedType")
  private FailedTypeEnum failedType = null;

  @SerializedName("parentFolderName")
  private String parentFolderName = null;

  @SerializedName("parentFolderId")
  private UUID parentFolderId = null;

  @SerializedName("errorMessage")
  private String errorMessage = null;

  public IFailedDownloadItem fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * The failed file name
   * @return fileName
  **/
  @ApiModelProperty(required = true, value = "The failed file name")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public IFailedDownloadItem failedType(FailedTypeEnum failedType) {
    this.failedType = failedType;
    return this;
  }

   /**
   * The failed type
   * @return failedType
  **/
  @ApiModelProperty(required = true, value = "The failed type")
  public FailedTypeEnum getFailedType() {
    return failedType;
  }

  public void setFailedType(FailedTypeEnum failedType) {
    this.failedType = failedType;
  }

  public IFailedDownloadItem parentFolderName(String parentFolderName) {
    this.parentFolderName = parentFolderName;
    return this;
  }

   /**
   * The parent folder Name
   * @return parentFolderName
  **/
  @ApiModelProperty(value = "The parent folder Name")
  public String getParentFolderName() {
    return parentFolderName;
  }

  public void setParentFolderName(String parentFolderName) {
    this.parentFolderName = parentFolderName;
  }

  public IFailedDownloadItem parentFolderId(UUID parentFolderId) {
    this.parentFolderId = parentFolderId;
    return this;
  }

   /**
   * The parent folder id
   * @return parentFolderId
  **/
  @ApiModelProperty(example = "00000000-0000-0000-0000-000000000000", value = "The parent folder id")
  public UUID getParentFolderId() {
    return parentFolderId;
  }

  public void setParentFolderId(UUID parentFolderId) {
    this.parentFolderId = parentFolderId;
  }

  public IFailedDownloadItem errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * The failed reason
   * @return errorMessage
  **/
  @ApiModelProperty(required = true, value = "The failed reason")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IFailedDownloadItem ifailedDownloadItem = (IFailedDownloadItem) o;
    return Objects.equals(this.fileName, ifailedDownloadItem.fileName) &&
        Objects.equals(this.failedType, ifailedDownloadItem.failedType) &&
        Objects.equals(this.parentFolderName, ifailedDownloadItem.parentFolderName) &&
        Objects.equals(this.parentFolderId, ifailedDownloadItem.parentFolderId) &&
        Objects.equals(this.errorMessage, ifailedDownloadItem.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileName, failedType, parentFolderName, parentFolderId, errorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IFailedDownloadItem {\n");
    
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    failedType: ").append(toIndentedString(failedType)).append("\n");
    sb.append("    parentFolderName: ").append(toIndentedString(parentFolderName)).append("\n");
    sb.append("    parentFolderId: ").append(toIndentedString(parentFolderId)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

