/*
 * Speech Services API v3.0-beta1
 * Speech Services API v3.0-beta1.
 *
 * OpenAPI spec version: v3.0-beta1
 * Contact: crservice@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * IReadOnlyDictionary2
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-02T13:09:27.002+08:00")
public class IReadOnlyDictionary2 {
  @SerializedName("None")
  private List<String> none = null;

  @SerializedName("Language")
  private List<String> language = null;

  @SerializedName("Acoustic")
  private List<String> acoustic = null;

  @SerializedName("Pronunciation")
  private List<String> pronunciation = null;

  @SerializedName("CustomVoice")
  private List<String> customVoice = null;

  @SerializedName("LanguageGeneration")
  private List<String> languageGeneration = null;

  @SerializedName("AudioFiles")
  private List<String> audioFiles = null;

  public IReadOnlyDictionary2 none(List<String> none) {
    this.none = none;
    return this;
  }

  public IReadOnlyDictionary2 addNoneItem(String noneItem) {
    if (this.none == null) {
      this.none = new ArrayList<String>();
    }
    this.none.add(noneItem);
    return this;
  }

   /**
   * Get none
   * @return none
  **/
  @ApiModelProperty(value = "")
  public List<String> getNone() {
    return none;
  }

  public void setNone(List<String> none) {
    this.none = none;
  }

  public IReadOnlyDictionary2 language(List<String> language) {
    this.language = language;
    return this;
  }

  public IReadOnlyDictionary2 addLanguageItem(String languageItem) {
    if (this.language == null) {
      this.language = new ArrayList<String>();
    }
    this.language.add(languageItem);
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(value = "")
  public List<String> getLanguage() {
    return language;
  }

  public void setLanguage(List<String> language) {
    this.language = language;
  }

  public IReadOnlyDictionary2 acoustic(List<String> acoustic) {
    this.acoustic = acoustic;
    return this;
  }

  public IReadOnlyDictionary2 addAcousticItem(String acousticItem) {
    if (this.acoustic == null) {
      this.acoustic = new ArrayList<String>();
    }
    this.acoustic.add(acousticItem);
    return this;
  }

   /**
   * Get acoustic
   * @return acoustic
  **/
  @ApiModelProperty(value = "")
  public List<String> getAcoustic() {
    return acoustic;
  }

  public void setAcoustic(List<String> acoustic) {
    this.acoustic = acoustic;
  }

  public IReadOnlyDictionary2 pronunciation(List<String> pronunciation) {
    this.pronunciation = pronunciation;
    return this;
  }

  public IReadOnlyDictionary2 addPronunciationItem(String pronunciationItem) {
    if (this.pronunciation == null) {
      this.pronunciation = new ArrayList<String>();
    }
    this.pronunciation.add(pronunciationItem);
    return this;
  }

   /**
   * Get pronunciation
   * @return pronunciation
  **/
  @ApiModelProperty(value = "")
  public List<String> getPronunciation() {
    return pronunciation;
  }

  public void setPronunciation(List<String> pronunciation) {
    this.pronunciation = pronunciation;
  }

  public IReadOnlyDictionary2 customVoice(List<String> customVoice) {
    this.customVoice = customVoice;
    return this;
  }

  public IReadOnlyDictionary2 addCustomVoiceItem(String customVoiceItem) {
    if (this.customVoice == null) {
      this.customVoice = new ArrayList<String>();
    }
    this.customVoice.add(customVoiceItem);
    return this;
  }

   /**
   * Get customVoice
   * @return customVoice
  **/
  @ApiModelProperty(value = "")
  public List<String> getCustomVoice() {
    return customVoice;
  }

  public void setCustomVoice(List<String> customVoice) {
    this.customVoice = customVoice;
  }

  public IReadOnlyDictionary2 languageGeneration(List<String> languageGeneration) {
    this.languageGeneration = languageGeneration;
    return this;
  }

  public IReadOnlyDictionary2 addLanguageGenerationItem(String languageGenerationItem) {
    if (this.languageGeneration == null) {
      this.languageGeneration = new ArrayList<String>();
    }
    this.languageGeneration.add(languageGenerationItem);
    return this;
  }

   /**
   * Get languageGeneration
   * @return languageGeneration
  **/
  @ApiModelProperty(value = "")
  public List<String> getLanguageGeneration() {
    return languageGeneration;
  }

  public void setLanguageGeneration(List<String> languageGeneration) {
    this.languageGeneration = languageGeneration;
  }

  public IReadOnlyDictionary2 audioFiles(List<String> audioFiles) {
    this.audioFiles = audioFiles;
    return this;
  }

  public IReadOnlyDictionary2 addAudioFilesItem(String audioFilesItem) {
    if (this.audioFiles == null) {
      this.audioFiles = new ArrayList<String>();
    }
    this.audioFiles.add(audioFilesItem);
    return this;
  }

   /**
   * Get audioFiles
   * @return audioFiles
  **/
  @ApiModelProperty(value = "")
  public List<String> getAudioFiles() {
    return audioFiles;
  }

  public void setAudioFiles(List<String> audioFiles) {
    this.audioFiles = audioFiles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IReadOnlyDictionary2 ireadOnlyDictionary2 = (IReadOnlyDictionary2) o;
    return Objects.equals(this.none, ireadOnlyDictionary2.none) &&
        Objects.equals(this.language, ireadOnlyDictionary2.language) &&
        Objects.equals(this.acoustic, ireadOnlyDictionary2.acoustic) &&
        Objects.equals(this.pronunciation, ireadOnlyDictionary2.pronunciation) &&
        Objects.equals(this.customVoice, ireadOnlyDictionary2.customVoice) &&
        Objects.equals(this.languageGeneration, ireadOnlyDictionary2.languageGeneration) &&
        Objects.equals(this.audioFiles, ireadOnlyDictionary2.audioFiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(none, language, acoustic, pronunciation, customVoice, languageGeneration, audioFiles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IReadOnlyDictionary2 {\n");
    
    sb.append("    none: ").append(toIndentedString(none)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    acoustic: ").append(toIndentedString(acoustic)).append("\n");
    sb.append("    pronunciation: ").append(toIndentedString(pronunciation)).append("\n");
    sb.append("    customVoice: ").append(toIndentedString(customVoice)).append("\n");
    sb.append("    languageGeneration: ").append(toIndentedString(languageGeneration)).append("\n");
    sb.append("    audioFiles: ").append(toIndentedString(audioFiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

