/*
 * Speech Services API v3.0-beta1
 * Speech Services API v3.0-beta1.
 *
 * OpenAPI spec version: v3.0-beta1
 * Contact: crservice@microsoft.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ModelIdentity;
import io.swagger.client.model.ProjectIdentity;
import java.io.IOException;

/**
 * VoiceTestDefinitionV30
 */
public class VoiceTestDefinitionV30 {
  @SerializedName("project")
  private ProjectIdentity project = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("model")
  private ModelIdentity model = null;

  /**
   * The kind of this test (e.g. Text, SSML)
   */
  @JsonAdapter(VoiceTestKindEnum.Adapter.class)
  public enum VoiceTestKindEnum {
    NONE("None"),
    
    TEXT("Text"),
    
    SSML("SSML");

    private String value;

    VoiceTestKindEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static VoiceTestKindEnum fromValue(String text) {
      for (VoiceTestKindEnum b : VoiceTestKindEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<VoiceTestKindEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final VoiceTestKindEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public VoiceTestKindEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return VoiceTestKindEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("voiceTestKind")
  private VoiceTestKindEnum voiceTestKind = null;

  public VoiceTestDefinitionV30 project(ProjectIdentity project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @ApiModelProperty(value = "")
  public ProjectIdentity getProject() {
    return project;
  }

  public void setProject(ProjectIdentity project) {
    this.project = project;
  }

  public VoiceTestDefinitionV30 text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Information about the text used in the voice test
   * @return text
  **/
  @ApiModelProperty(required = true, value = "Information about the text used in the voice test")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public VoiceTestDefinitionV30 model(ModelIdentity model) {
    this.model = model;
    return this;
  }

   /**
   * Information about the models used in the voice test
   * @return model
  **/
  @ApiModelProperty(required = true, value = "Information about the models used in the voice test")
  public ModelIdentity getModel() {
    return model;
  }

  public void setModel(ModelIdentity model) {
    this.model = model;
  }

  public VoiceTestDefinitionV30 voiceTestKind(VoiceTestKindEnum voiceTestKind) {
    this.voiceTestKind = voiceTestKind;
    return this;
  }

   /**
   * The kind of this test (e.g. Text, SSML)
   * @return voiceTestKind
  **/
  @ApiModelProperty(required = true, value = "The kind of this test (e.g. Text, SSML)")
  public VoiceTestKindEnum getVoiceTestKind() {
    return voiceTestKind;
  }

  public void setVoiceTestKind(VoiceTestKindEnum voiceTestKind) {
    this.voiceTestKind = voiceTestKind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoiceTestDefinitionV30 voiceTestDefinitionV30 = (VoiceTestDefinitionV30) o;
    return Objects.equals(this.project, voiceTestDefinitionV30.project) &&
        Objects.equals(this.text, voiceTestDefinitionV30.text) &&
        Objects.equals(this.model, voiceTestDefinitionV30.model) &&
        Objects.equals(this.voiceTestKind, voiceTestDefinitionV30.voiceTestKind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(project, text, model, voiceTestKind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoiceTestDefinitionV30 {\n");
    
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    voiceTestKind: ").append(toIndentedString(voiceTestKind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

